on:
  push:
    branches:
      - main
      - master

name: distill

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Cache Renv packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore(packages = "renv")'
          R -e 'renv::restore()'

      - name: Build slides
        run: Rscript -e 'purrr::map(list.files(path = "slides",pattern = ".Rmd",full.names = TRUE),~rmarkdown::render(.x))'
          
      - name: Build site
        run: Rscript -e 'rmarkdown::render_site()'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
          publish_dir: docs/                     # "public/" by default